package view;

import controller.SimulacaoController;
import javax.swing.JPanel;

public class JanelaSimulacao extends javax.swing.JFrame {
    public JanelaSimulacao() {
        initComponents();
        addAnimationPanel();
        
        c = new SimulacaoController(this);
    }

    public JPanel getJpOnda1() {
        return jpOnda5;
    }
    public void setJpOnda1(JPanel jpOnda1) {
        this.jpOnda5 = jpOnda1;
    }

    public JPanel getJpOnda2() {
        return jpOnda4;
    }
    public void setJpOnda2(JPanel jpOnda2) {
        this.jpOnda4 = jpOnda2;
    }

    public JPanel getJpOnda3() {
        return jpOnda3;
    }
    public void setJpOnda3(JPanel jpOnda3) {
        this.jpOnda3 = jpOnda3;
    }

    public JPanel getJpOnda4() {
        return jpOnda2;
    }
    public void setJpOnda4(JPanel jpOnda4) {
        this.jpOnda2 = jpOnda4;
    }

    public JPanel getJpOnda5() {
        return jpOnda1;
    }
    public void setJpOnda5(JPanel jpOnda5) {
        this.jpOnda1 = jpOnda5;
    }

    public JPanel getJpAni1() {
        return jpAni1;
    }
    public void setJpAni1(JPanel jpAni1) {
        this.jpAni1 = jpAni1;
    }

    public JPanel getJpAni2() {
        return jpAni2;
    }
    public void setJpAni2(JPanel jpAni2) {
        this.jpAni2 = jpAni2;
    }

    public SimulacaoController getC(){
        return c;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btIniciar = new javax.swing.JButton();
        btParar = new javax.swing.JButton();
        jpOndas = new javax.swing.JPanel();
        jpOnda5 = new OndaPanel();
        jpOnda4 = new OndaPanel();
        jpOnda3 = new OndaPanel();
        jpOnda2 = new OndaPanel();
        jpOnda1 = new OndaPanel();
        jpAni2 = new FotonPanel();
        lblN5 = new javax.swing.JLabel();
        lblN4 = new javax.swing.JLabel();
        lblN2 = new javax.swing.JLabel();
        lblN3 = new javax.swing.JLabel();
        lblN1 = new javax.swing.JLabel();
        jpAni1 = new FotonPanel();

        setTitle("Simulação");
        setResizable(false);
        setSize(new java.awt.Dimension(835, 740));

        btIniciar.setText("Iniciar");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        btParar.setText("Parar");
        btParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPararActionPerformed(evt);
            }
        });

        jpOndas.setBackground(new java.awt.Color(238, 238, 238));
        jpOndas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpOnda5.setToolTipText("");
        jpOnda5.setAlignmentX(1.0F);
        jpOnda5.setAlignmentY(1.0F);
        jpOnda5.setName(""); // NOI18N
        jpOnda5.setPreferredSize(new java.awt.Dimension(400, 131));
        jpOnda5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpOnda4.setPreferredSize(new java.awt.Dimension(400, 131));
        jpOnda4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpOnda3.setPreferredSize(new java.awt.Dimension(400, 131));
        jpOnda3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpOnda2.setPreferredSize(new java.awt.Dimension(400, 131));
        jpOnda2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpOnda1.setPreferredSize(new java.awt.Dimension(400, 131));
        jpOnda1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jpOndasLayout = new javax.swing.GroupLayout(jpOndas);
        jpOndas.setLayout(jpOndasLayout);
        jpOndasLayout.setHorizontalGroup(
            jpOndasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(jpOndasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpOndasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpOndasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpOnda5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpOnda4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpOnda3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpOnda2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpOnda1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpOndasLayout.setVerticalGroup(
            jpOndasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(jpOndasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpOndasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpOnda5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpOnda4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpOnda3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpOnda2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpOnda1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jpOnda5.getAccessibleContext().setAccessibleName("");

        lblN5.setText("N = 5");

        lblN4.setText("N = 4");

        lblN2.setText("N = 2");

        lblN3.setText("N = 3");

        lblN1.setText("N = 1");

        javax.swing.GroupLayout jpAni2Layout = new javax.swing.GroupLayout(jpAni2);
        jpAni2.setLayout(jpAni2Layout);
        jpAni2Layout.setHorizontalGroup(
            jpAni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAni2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblN5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jpAni2Layout.setVerticalGroup(
            jpAni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAni2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblN5)
                .addGap(98, 98, 98)
                .addComponent(lblN4)
                .addGap(98, 98, 98)
                .addComponent(lblN3)
                .addGap(103, 103, 103)
                .addComponent(lblN2)
                .addGap(113, 113, 113)
                .addComponent(lblN1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpAni1Layout = new javax.swing.GroupLayout(jpAni1);
        jpAni1.setLayout(jpAni1Layout);
        jpAni1Layout.setHorizontalGroup(
            jpAni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jpAni1Layout.setVerticalGroup(
            jpAni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpAni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpOndas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btIniciar)
                        .addGap(76, 76, 76)
                        .addComponent(btParar)
                        .addGap(101, 101, 101)))
                .addComponent(jpAni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpOndas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btIniciar)
                    .addComponent(btParar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpAni1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpAni2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        c.iniciarAnimacao();
    }//GEN-LAST:event_btIniciarActionPerformed

    private void btPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPararActionPerformed
        c.stopSimulacao();
    }//GEN-LAST:event_btPararActionPerformed

    private void addAnimationPanel(){
        FotonPanel fotonPanel = new FotonPanel();
        
        fotonPanel.setBounds(0, 0, getWidth(), getHeight());
        fotonPanel.setOpaque(false);
        
        this.getContentPane().setLayout(null);
        this.add(fotonPanel);
        
        this.repaint();
    }

    private final SimulacaoController c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btParar;
    private javax.swing.JPanel jpAni1;
    private javax.swing.JPanel jpAni2;
    private javax.swing.JPanel jpOnda1;
    private javax.swing.JPanel jpOnda2;
    private javax.swing.JPanel jpOnda3;
    private javax.swing.JPanel jpOnda4;
    private javax.swing.JPanel jpOnda5;
    private javax.swing.JPanel jpOndas;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblN3;
    private javax.swing.JLabel lblN4;
    private javax.swing.JLabel lblN5;
    // End of variables declaration//GEN-END:variables
}
